# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build
      run: |
        npm install
        npm run-script deploy
        cp dist/spotify-stats/index.html dist/spotify-stats/404.html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/spotify-stats
        TARGET_FOLDER: docs
